version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: repo-analyzer-backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      # OpenAI API key - set this environment variable on your system
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount for temporary repository cloning
      - repo_temp:/tmp/repo-analysis
    networks:
      - repo-analyzer-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: repo-analyzer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - repo-analyzer-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  repo_temp:
    driver: local

networks:
  repo-analyzer-network:
    driver: bridge
