services:
  - type: web
    name: repo-analyzer
    env: docker
    dockerfilePath: ./Dockerfile.combined
    plan: starter
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: GO_ENV
        value: production
      - key: PORT
        value: "8080"
